//! Emits `light-poseidon/src/parameters/bn254_x5_sparse.rs`.

use std::{fmt::Write as _, fs::File, io::Write as _, path::PathBuf, process::Command};

use anyhow::anyhow;
use clap::Parser;

use super::{derive, format_field_element, verify, Optimized, RoundParameters};

/// Widths covered by the bundled BN254 parameters.
const WIDTHS: std::ops::RangeInclusive<u8> = 2..=13;

/// Pseudo-random permutation samples compared against the reference per width.
const VERIFICATION_SAMPLES: usize = 64;

const OUTPUT_PATH: &str = "./light-poseidon/src/parameters/bn254_x5_sparse.rs";

#[derive(Debug, Parser)]
pub struct Options {
    /// Derive and verify the constants without writing the generated file.
    #[clap(long)]
    pub check: bool,
    /// Where to write the generated file.
    #[clap(long)]
    pub path: Option<PathBuf>,
}

pub fn generate_sparse_mds_parameters(opts: Options) -> Result<(), anyhow::Error> {
    let mut derived = Vec::new();
    for t in WIDTHS {
        let params = RoundParameters::load(t)?;
        let optimized = derive(&params)?;
        verify(&params, &optimized, VERIFICATION_SAMPLES)?;
        println!(
            "width {t}: {} partial rounds verified against the reference permutation",
            params.partial_rounds
        );
        derived.push((params, optimized));
    }

    if opts.check {
        println!("all widths verified; not writing the generated file (--check)");
        return Ok(());
    }

    let code = render(&derived)?;
    let path = opts
        .path
        .unwrap_or_else(|| PathBuf::from(OUTPUT_PATH));
    let mut file = File::create(&path)?;
    file.write_all(code.as_bytes())?;
    println!("Sparse-MDS parameters written to {path:?}");

    Command::new("cargo")
        .arg("fmt")
        .output()
        .map_err(|e| anyhow!("cargo fmt failed: {e}"))?;
    Ok(())
}

fn render(derived: &[(RoundParameters, Optimized)]) -> Result<String, anyhow::Error> {
    let mut code = String::new();
    code += "// This file is generated by xtask. Do not edit it manually.\n\n";
    code += HEADER;

    for (params, optimized) in derived {
        let width = params.width;

        let pre = optimized.pre.as_slice();
        write!(
            code,
            "\n/// Pre-sparse matrix for width {width}, flat row-major.\npub static PRE_{width}: [Fr; {}] = [\n",
            pre.len()
        )?;
        for element in pre {
            code += &format_field_element(element);
        }
        code += "];\n";

        let entries_per_matrix = 2 * width - 1;
        write!(
            code,
            "\n/// Sparse partial-round matrices for width {width}, in application\n/// order, {entries_per_matrix} entries each.\npub static SPARSE_{width}: [Fr; {}] = [\n",
            optimized.matrices.len() * entries_per_matrix
        )?;
        for matrix in &optimized.matrices {
            if matrix.row.len() != width || matrix.column.len() + 1 != width {
                return Err(anyhow!(
                    "width {width}: sparse matrix has a {}-entry row and a {}-entry column",
                    matrix.row.len(),
                    matrix.column.len()
                ));
            }
            for element in matrix.row.iter().chain(matrix.column.iter()) {
                code += &format_field_element(element);
            }
        }
        code += "];\n";

        write!(
            code,
            "\n/// Folded partial-round constants for width {width}, one per round.\npub static PARTIAL_ARK_{width}: [Fr; {}] = [\n",
            optimized.ark.len()
        )?;
        for element in &optimized.ark {
            code += &format_field_element(element);
        }
        code += "];\n";

        write!(
            code,
            "\n/// Constant added to the width-{width} state after the partial rounds.\npub static POST_{width}: [Fr; {}] = [\n",
            optimized.post.len()
        )?;
        for element in &optimized.post {
            code += &format_field_element(element);
        }
        code += "];\n";
    }

    code += "\n/// Returns the sparse-MDS decomposition of the partial rounds for width\n\
             /// `t`, or `None` when no decomposition is bundled for that width.\n\
             pub fn get_sparse_mds_parameters(t: u8) -> Option<SparseMdsParameters<Fr>> {\n\
             \x20   match t {\n";
    for (params, _) in derived {
        let width = params.width;
        write!(
            code,
            "        {width} => Some(SparseMdsParameters {{\n\
             \x20           pre: &PRE_{width},\n\
             \x20           matrices: &SPARSE_{width},\n\
             \x20           ark: &PARTIAL_ARK_{width},\n\
             \x20           post: &POST_{width},\n\
             \x20       }}),\n"
        )?;
    }
    code += "        _ => None,\n    }\n}\n";

    Ok(code)
}

const HEADER: &str = "\
//! Sparse-MDS constants for the partial rounds of the BN254 x^5 permutation.
//!
//! A partial round applies the S-box to `state[0]` only, yet the reference
//! round still multiplies by the full MDS matrix, costing `width^2` field
//! multiplications. The constants here implement the standard factorization
//! from appendix B of the Poseidon paper, which replaces each partial round's
//! matrix with one that is the identity outside its first row and column, so a
//! partial round costs `2 * width - 1` multiplications instead.
//!
//! The rewrite is an exact identity over the field: the permutation, and every
//! hash output, are unchanged. `cargo xtask generate-sparse-mds-parameters
//! --check` re-derives these constants and checks both the underlying matrix
//! identities and end-to-end equality against the unoptimized permutation.

use ark_bn254::Fr;
use ark_ff::BigInteger256;

use crate::SparseMdsParameters;
";

/// Sanity check kept next to the emitter: the derivation must be stable, so
/// deriving twice has to produce the same constants.
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn derivation_is_deterministic() {
        for t in WIDTHS {
            let params = RoundParameters::load(t).unwrap();
            let first = derive(&params).unwrap();
            let second = derive(&params).unwrap();
            assert_eq!(first.pre, second.pre);
            assert_eq!(first.matrices, second.matrices);
            assert_eq!(first.ark, second.ark);
            assert_eq!(first.post, second.post);
        }
    }

    #[test]
    fn derivation_matches_the_reference_permutation() {
        for t in WIDTHS {
            let params = RoundParameters::load(t).unwrap();
            let optimized = derive(&params).unwrap();
            verify(&params, &optimized, VERIFICATION_SAMPLES).unwrap();
        }
    }
}
